//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Userbox.Resources {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Userbox.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancella record.
        /// </summary>
        public static string AltTitleDelete {
            get {
                return ResourceManager.GetString("AltTitleDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vedi dettagli record.
        /// </summary>
        public static string AltTitleDetails {
            get {
                return ResourceManager.GetString("AltTitleDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica record.
        /// </summary>
        public static string AltTitleEdit {
            get {
                return ResourceManager.GetString("AltTitleEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vedi dettagli da Identity.
        /// </summary>
        public static string AltTitleIdentityDetails {
            get {
                return ResourceManager.GetString("AltTitleIdentityDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Vedi dettagli da Ldap.
        /// </summary>
        public static string AltTitleLdapDetails {
            get {
                return ResourceManager.GetString("AltTitleLdapDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attiva.
        /// </summary>
        public static string BtnActivate {
            get {
                return ResourceManager.GetString("BtnActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attiva firma.
        /// </summary>
        public static string BtnActivateSign {
            get {
                return ResourceManager.GetString("BtnActivateSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Torna alla Ricerca.
        /// </summary>
        public static string BtnBackToSearch {
            get {
                return ResourceManager.GetString("BtnBackToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci.
        /// </summary>
        public static string BtnCreate {
            get {
                return ResourceManager.GetString("BtnCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Disattiva.
        /// </summary>
        public static string BtnDeactivate {
            get {
                return ResourceManager.GetString("BtnDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettagli.
        /// </summary>
        public static string BtnDetails {
            get {
                return ResourceManager.GetString("BtnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica.
        /// </summary>
        public static string BtnEdit {
            get {
                return ResourceManager.GetString("BtnEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica cellulare.
        /// </summary>
        public static string BtnEditPhone {
            get {
                return ResourceManager.GetString("BtnEditPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Impersona.
        /// </summary>
        public static string BtnImpersonate {
            get {
                return ResourceManager.GetString("BtnImpersonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco.
        /// </summary>
        public static string BtnList {
            get {
                return ResourceManager.GetString("BtnList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esci.
        /// </summary>
        public static string BtnLogoff {
            get {
                return ResourceManager.GetString("BtnLogoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logout.
        /// </summary>
        public static string BtnLogout {
            get {
                return ResourceManager.GetString("BtnLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nuovo.
        /// </summary>
        public static string BtnNew {
            get {
                return ResourceManager.GetString("BtnNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Sospendi.
        /// </summary>
        public static string BtnPause {
            get {
                return ResourceManager.GetString("BtnPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Riattiva.
        /// </summary>
        public static string BtnReActivate {
            get {
                return ResourceManager.GetString("BtnReActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Reset utente.
        /// </summary>
        public static string BtnResetUser {
            get {
                return ResourceManager.GetString("BtnResetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Gestisci ruoli.
        /// </summary>
        public static string BtnRoles {
            get {
                return ResourceManager.GetString("BtnRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Salva.
        /// </summary>
        public static string BtnSave {
            get {
                return ResourceManager.GetString("BtnSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Esporta.
        /// </summary>
        public static string BtnSaveAs_Excel {
            get {
                return ResourceManager.GetString("BtnSaveAs_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Stampa.
        /// </summary>
        public static string BtnSaveAs_Pdf {
            get {
                return ResourceManager.GetString("BtnSaveAs_Pdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca.
        /// </summary>
        public static string BtnSearch {
            get {
                return ResourceManager.GetString("BtnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Condividi.
        /// </summary>
        public static string BtnShare {
            get {
                return ResourceManager.GetString("BtnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Revoca.
        /// </summary>
        public static string BtnStop {
            get {
                return ResourceManager.GetString("BtnStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Revoca da sospeso.
        /// </summary>
        public static string BtnStopFromPause {
            get {
                return ResourceManager.GetString("BtnStopFromPause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Carica file.
        /// </summary>
        public static string BtnUpload_File {
            get {
                return ResourceManager.GetString("BtnUpload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Country.
        /// </summary>
        public static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome completo.
        /// </summary>
        public static string CN {
            get {
                return ResourceManager.GetString("CN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a dnQualifier.
        /// </summary>
        public static string dnQualifier {
            get {
                return ResourceManager.GetString("dnQualifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Email.
        /// </summary>
        public static string E {
            get {
                return ResourceManager.GetString("E", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a {0} deve essere compreso tra  {1} e {2}.
        /// </summary>
        public static string ErrorRange {
            get {
                return ResourceManager.GetString("ErrorRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string G {
            get {
                return ResourceManager.GetString("G", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Attivo.
        /// </summary>
        public static string LblActive {
            get {
                return ResourceManager.GetString("LblActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Indirizzo.
        /// </summary>
        public static string LblAddress {
            get {
                return ResourceManager.GetString("LblAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Data inserimento.
        /// </summary>
        public static string LblCreationDate {
            get {
                return ResourceManager.GetString("LblCreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Descrizione.
        /// </summary>
        public static string LblDescr {
            get {
                return ResourceManager.GetString("LblDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string LblLastName {
            get {
                return ResourceManager.GetString("LblLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Nome.
        /// </summary>
        public static string LblName {
            get {
                return ResourceManager.GetString("LblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ricerca.
        /// </summary>
        public static string LblSearch {
            get {
                return ResourceManager.GetString("LblSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Termine ricerca.
        /// </summary>
        public static string LblSearchTerm {
            get {
                return ResourceManager.GetString("LblSearchTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Tipo ricerca.
        /// </summary>
        public static string LblSearchType {
            get {
                return ResourceManager.GetString("LblSearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Testo.
        /// </summary>
        public static string LblText {
            get {
                return ResourceManager.GetString("LblText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Titolo.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Unipi username.
        /// </summary>
        public static string LblUnipiUserName {
            get {
                return ResourceManager.GetString("LblUnipiUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Username.
        /// </summary>
        public static string LblUsername {
            get {
                return ResourceManager.GetString("LblUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Identity.
        /// </summary>
        public static string LblUtente_IdentityUsers {
            get {
                return ResourceManager.GetString("LblUtente_IdentityUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ldap.
        /// </summary>
        public static string LblUtente_LdapUsers {
            get {
                return ResourceManager.GetString("LblUtente_LdapUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utente.
        /// </summary>
        public static string LblUtente_User {
            get {
                return ResourceManager.GetString("LblUtente_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utenti.
        /// </summary>
        public static string LblUtente_Users {
            get {
                return ResourceManager.GetString("LblUtente_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Autorilascio firma elettronica.
        /// </summary>
        public static string MenuMain_AutoEnrollment {
            get {
                return ResourceManager.GetString("MenuMain_AutoEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Configurazioni.
        /// </summary>
        public static string MenuMain_Configuration {
            get {
                return ResourceManager.GetString("MenuMain_Configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Home.
        /// </summary>
        public static string MenuMain_Home {
            get {
                return ResourceManager.GetString("MenuMain_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logs.
        /// </summary>
        public static string MenuMain_Logs {
            get {
                return ResourceManager.GetString("MenuMain_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Ospiti.
        /// </summary>
        public static string MenuMain_Ospiti {
            get {
                return ResourceManager.GetString("MenuMain_Ospiti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Crea.
        /// </summary>
        public static string MenuMain_Ospiti_Crea {
            get {
                return ResourceManager.GetString("MenuMain_Ospiti_Crea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Lista.
        /// </summary>
        public static string MenuMain_Ospiti_Visualizza {
            get {
                return ResourceManager.GetString("MenuMain_Ospiti_Visualizza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Termini e condizioni.
        /// </summary>
        public static string MenuMain_TermsConditions {
            get {
                return ResourceManager.GetString("MenuMain_TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Utenti.
        /// </summary>
        public static string MenuMain_Users {
            get {
                return ResourceManager.GetString("MenuMain_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Logout.
        /// </summary>
        public static string MenuTop_Logout {
            get {
                return ResourceManager.GetString("MenuTop_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Confermi di voler modificare questo record?.
        /// </summary>
        public static string Msg_ChangeRecord {
            get {
                return ResourceManager.GetString("Msg_ChangeRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Seleziona un.
        /// </summary>
        public static string Select2Msg_SelectItem {
            get {
                return ResourceManager.GetString("Select2Msg_SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Codice fiscale.
        /// </summary>
        public static string SERIALNUMBER {
            get {
                return ResourceManager.GetString("SERIALNUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cognome.
        /// </summary>
        public static string SN {
            get {
                return ResourceManager.GetString("SN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Inserisci.
        /// </summary>
        public static string TltCreate {
            get {
                return ResourceManager.GetString("TltCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Cancella.
        /// </summary>
        public static string TltDelete {
            get {
                return ResourceManager.GetString("TltDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettaglio.
        /// </summary>
        public static string TltDetail {
            get {
                return ResourceManager.GetString("TltDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Dettagli.
        /// </summary>
        public static string TltDetails {
            get {
                return ResourceManager.GetString("TltDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Modifica.
        /// </summary>
        public static string TltEdit {
            get {
                return ResourceManager.GetString("TltEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Elenco.
        /// </summary>
        public static string TltList {
            get {
                return ResourceManager.GetString("TltList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valido dal.
        /// </summary>
        public static string ValidFrom {
            get {
                return ResourceManager.GetString("ValidFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a Valido fino al.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
    }
}
